### PR TITLE
Create shell_sort.cpp

### PR DESCRIPTION
**Pull request by ruturaj-gh**
added shell sort code 
happy hactoberfest23 !!

### CODE REVIEW

**Comment by Nikhil-2002** [comment]
hey bro event will start in 1st oct then i'll accept pull requests..

**Review by Nikhil-2002 — APPROVED** [review]
All are good

**Comment by ruturaj-gh** [comment]
Ok no problem

**Review by Nikhil-2002 — COMMENTED** [review]
done

**Comment by ruturaj-gh** [comment]
Hey @Nikhil-2002 it is not showing on waiting list, i think  you also need to add hactoberfest label.

**Comment by Nikhil-2002** [comment]
already added I don't know what going wrong

**Comment by ruturaj-gh** [comment]
Yeah ! you have added `hactoberfest-accepted` and `hactoberfest2023` but not `hactoberfest` i guess that's why it's not showing

**Pull request merged**
